-- Seed Database for Rules Engine

INSERT INTO rule_sections (code, name, description, sort_order, is_active) VALUES
('LINK', 'Link & Domain', 'Rules liên quan đến đường link', 1, true),
('CONTENT', 'Content', 'Rules bảo vệ thương hiệu và tính toàn vẹn nội dung', 2, true),
('MEDICAL', 'Medical', 'Rules an toàn y tế', 3, true),
('FORMAT', 'Format', 'Rules định dạng văn bản', 4, true),
('SOURCE', 'Source', 'Rules về nguồn tham khảo', 5, true)
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;

INSERT INTO rules (
  section_id, code, name, description, check_type, check_config,
  deduction, max_deduction, auto_fixable, fix_instruction, severity,
  applies_to, scope, is_system
) VALUES
(
  (SELECT id FROM rule_sections WHERE code = 'LINK'),
  'LINK_no_external_in_content',
  'Không chèn link ngoài trong nội dung bài viết',
  'Phần nội dung chỉ được chứa link đến domain nội bộ Long Châu. Không được link đến bất kỳ website nào khác kể cả nguồn học thuật — nguồn chỉ được phép ở phần tham khảo cuối bài.',
  'no_external_link',
  '{"check_section":"content_only","exclude_section":"references","load_allowed_from":"rule_domain_configs.allowed_internal_domains"}'::jsonb,
  10,
  10,
  false,
  NULL,
  'critical',
  ARRAY['*'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'LINK'),
  'LINK_no_cross_domain',
  'Không cross-link giữa nhathuoclongchau và tiemchunglongchau',
  'Bài viết thuộc website nhà thuốc không được link sang website tiêm chủng và ngược lại. Hai hệ thống hoạt động độc lập về SEO và nội dung.',
  'no_cross_domain',
  '{"load_groups_from":"rule_domain_configs.cross_domain_groups","detect_article_domain_from":"article.target_website","message":"Phát hiện cross-link giữa 2 domain — xóa hoặc thay bằng link cùng domain"}'::jsonb,
  10,
  10,
  false,
  NULL,
  'critical',
  ARRAY['*'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'LINK'),
  'LINK_anchor_no_vague',
  'Anchor text không được mơ hồ',
  'Không dùng anchor text: "tại đây", "xem thêm", "click vào đây", "ở đây", "bài viết này", "nhấn vào", "link này". Anchor text phải là keyword mô tả nội dung trang đích.',
  'regex',
  '{"pattern":"href[^>]*>\\s*(?:tại đây|xem thêm|click(?: vào)?|ở đây|bài viết này|nhấn vào|link này)\\s*<","flag_matches":true,"message":"Anchor text mơ hồ — thay bằng keyword mô tả trang đích"}'::jsonb,
  2,
  6,
  false,
  NULL,
  'warning',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'LINK'),
  'LINK_ref_domain_quality',
  'Nguồn tham khảo chỉ được là domain uy tín',
  'Phần nguồn tham khảo chỉ chấp nhận link từ danh sách domain học thuật được duyệt. Không chấp nhận: blog, báo điện tử trong nước, Wikipedia, web tổng hợp.',
  'reference_domain_check',
  '{"check_section":"references_only","load_allowed_from":"rule_domain_configs.allowed_reference_domains","message":"Domain nguồn tham khảo không nằm trong danh sách được duyệt"}'::jsonb,
  3,
  9,
  false,
  NULL,
  'critical',
  ARRAY['BENH_LY','THUOC','DUOC_LIEU','DUOC_CHAT','VACCINE_LE','VACCINE_GOI'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'LINK'),
  'LINK_no_blocked_domain',
  'Không chứa link từ domain bị chặn',
  'Phát hiện và xóa bất kỳ link nào đến domain trong danh sách blocked_domains bất kể ở section nào trong bài.',
  'blocked_domain_check',
  '{"check_section":"entire_article","load_blocked_from":"rule_domain_configs.blocked_domains"}'::jsonb,
  10,
  10,
  true,
  'Remove entire anchor tag, keep link text only',
  'critical',
  ARRAY['*'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'CONTENT'),
  'CONTENT_no_competitor',
  'Không đề cập tên đối thủ cạnh tranh',
  'Không được nhắc tên bất kỳ nhà thuốc, chuỗi dược phẩm hoặc thương hiệu y tế cạnh tranh với Long Châu dù là so sánh trực tiếp hay gián tiếp.',
  'custom_ai',
  '{"prompt":"Check if the article mentions any competitor pharmacy chains, drugstore brands, or competing medical services in Vietnam (excluding Long Châu). Return [{mention, context, location}] or empty array."}'::jsonb,
  10,
  10,
  false,
  NULL,
  'critical',
  ARRAY['*'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'CONTENT'),
  'CONTENT_no_negative_brand',
  'Không có nội dung tiêu cực về Long Châu hoặc nhãn hàng đối tác',
  'Bài viết không được chứa thông tin tiêu cực, so sánh bất lợi, hoặc nội dung gây hại cho thương hiệu Long Châu và các nhãn hàng đối tác kinh doanh.',
  'custom_ai',
  '{"prompt":"Check if article contains negative statements, unfavorable comparisons, or brand-damaging content about Long Châu pharmacy or its partner brands. Return [{text, reason}] or empty array."}'::jsonb,
  10,
  10,
  false,
  NULL,
  'critical',
  ARRAY['*'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'CONTENT'),
  'CONTENT_no_unverified_product',
  'Chỉ đề cập sản phẩm Long Châu đang kinh doanh',
  'Khi bài viết giới thiệu sản phẩm cụ thể của Long Châu, sản phẩm đó phải đang có trong danh mục kinh doanh thực tế. Flag để editor xác nhận thủ công.',
  'custom_ai',
  '{"prompt":"Find any specific product names mentioned as being sold by Long Châu. Return [{product_name, context}] for manual verification.","action":"flag_for_human_review"}'::jsonb,
  5,
  5,
  false,
  NULL,
  'warning',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'CONTENT'),
  'CONTENT_unique_score',
  'Unique content ≥ 90%',
  'Nội dung phải đạt tỉ lệ unique tối thiểu 90% khi kiểm tra plagiarism. Kiểm tra tại smallseotools.com trước khi publish.',
  'unique_score',
  '{"threshold_pass":90,"threshold_warn":80,"manual_check_tool":"smallseotools.com/plagiarism-checker","note":"AI không thể tự kiểm tra — editor phải check thủ công"}'::jsonb,
  5,
  10,
  false,
  NULL,
  'warning',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'MEDICAL'),
  'MEDICAL_no_cure_claim',
  'Không claim chữa khỏi hoàn toàn',
  'Không dùng ngôn ngữ khẳng định chữa khỏi: "chữa khỏi", "trị dứt điểm", "khỏi hẳn", "100% hiệu quả", "đảm bảo khỏi", "chữa hoàn toàn".',
  'regex',
  '{"pattern":"chữa khỏi|trị dứt điểm|khỏi hẳn|100% hiệu quả|đảm bảo khỏi|chữa hoàn toàn|điều trị dứt điểm|chữa được hoàn toàn","message":"Claim tuyệt đối về hiệu quả điều trị"}'::jsonb,
  5,
  10,
  true,
  'Replace absolute cure claims with: "có thể hỗ trợ điều trị", "giúp cải thiện triệu chứng", "theo chỉ định của bác sĩ"',
  'critical',
  ARRAY['*'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'MEDICAL'),
  'MEDICAL_no_superlative',
  'Không dùng ngôn ngữ thổi phồng hiệu quả',
  'Không dùng: "tốt nhất", "hiệu quả nhất", "số 1", "hàng đầu thế giới", "vô địch", "tuyệt vời nhất" khi mô tả sản phẩm hoặc phương pháp điều trị.',
  'regex',
  '{"pattern":"tốt nhất|hiệu quả nhất|số 1|hàng đầu thế giới|vô địch|tuyệt vời nhất|tốt nhất hiện nay|hiệu nghiệm nhất","message":"Ngôn ngữ thổi phồng không có dẫn chứng"}'::jsonb,
  3,
  6,
  true,
  'Remove superlative or replace with specific evidence-based description',
  'warning',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'MEDICAL'),
  'MEDICAL_recommend_doctor',
  'Bài điều trị phải có khuyến nghị gặp bác sĩ',
  'Bài viết có nội dung điều trị, liều dùng, hoặc hướng dẫn dùng thuốc phải có ít nhất 1 câu khuyến nghị tham khảo bác sĩ hoặc dược sĩ.',
  'custom_ai',
  '{"prompt":"If article discusses treatment protocols, medication dosage, or drug usage: check if it includes recommendation to consult a doctor or pharmacist. Return {has_recommendation: bool, location: string}.","applies_when":"article contains treatment or medication content"}'::jsonb,
  3,
  3,
  true,
  'Append to end of treatment section: "Người bệnh nên tham khảo ý kiến bác sĩ hoặc dược sĩ trước khi sử dụng."',
  'warning',
  ARRAY['BENH_LY','THUOC','DUOC_LIEU','DUOC_CHAT','NON_THUOC'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'MEDICAL'),
  'MEDICAL_nonthuoc_disclaimer',
  'Non-thuốc/TPCN phải có disclaimer bắt buộc',
  'Mọi bài viết về thực phẩm chức năng, CSCN, TTBYT phải có câu disclaimer: "Sản phẩm này không phải là thuốc và không có tác dụng thay thế thuốc chữa bệnh."',
  'regex',
  '{"pattern":"không phải là thuốc.*không có tác dụng thay thế","negate":true,"message":"Thiếu disclaimer bắt buộc cho sản phẩm non-thuốc"}'::jsonb,
  5,
  5,
  true,
  'Add at end of article: "Lưu ý: Sản phẩm này không phải là thuốc và không có tác dụng thay thế thuốc chữa bệnh."',
  'critical',
  ARRAY['NON_THUOC'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'MEDICAL'),
  'MEDICAL_vaccine_hdyk',
  'Bài vắc xin phải ghi chú nguồn HĐYK',
  'Tất cả thông tin về phác đồ tiêm, lịch tiêm, chống chỉ định trong bài vắc xin phải được ghi chú "(Theo phác đồ HĐYK)".',
  'custom_ai',
  '{"prompt":"Check if sections about vaccination schedule, contraindications, and dosage protocols include the note \"(Theo phác đồ HĐYK)\". Return {compliant: bool, missing_sections: []}."}'::jsonb,
  4,
  8,
  true,
  'Add "(Theo phác đồ HĐYK)" after each H2 heading related to vaccination schedule, contraindications, or dosage',
  'warning',
  ARRAY['VACCINE_LE','VACCINE_GOI'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_spelling',
  'Không sai chính tả tiếng Việt',
  NULL,
  'custom_ai',
  '{"prompt":"Check for Vietnamese spelling errors. Return [{error, correction, location, context}]. Focus on: dấu thanh, dấu mũ, phụ âm đầu (d/gi/r), vần (ai/ay, oi/ôi/ơi)."}'::jsonb,
  3,
  15,
  true,
  'Correct all spelling errors while preserving meaning and tone',
  'critical',
  ARRAY['*'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_bullet_symbol',
  'Liệt kê dùng dấu (•) không dùng (-) hoặc (+)',
  NULL,
  'regex',
  '{"pattern":"^\\s*[-+]\\s","multiline":true}'::jsonb,
  1,
  3,
  true,
  'Replace - or + at start of list lines with •',
  'info',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_unit_lowercase',
  'Đơn vị đo viết thường: mg, ml, mcg, IU',
  NULL,
  'regex',
  '{"pattern":"\\b(?:[Mm][Gg]|[Mm][Ll]|[Mm][Cc][Gg]|IU(?!\\s*[A-Z]))\\b","exclude_pattern":"^IU$"}'::jsonb,
  1,
  3,
  true,
  'Convert Mg→mg, Ml→ml, Mcg→mcg throughout',
  'info',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_colon_capitalize',
  'Viết hoa chữ đầu sau dấu hai chấm',
  NULL,
  'regex',
  '{"pattern":":\\s+[a-záàảãạăắằẳẵặâấầẩẫậđéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵ]"}'::jsonb,
  1,
  2,
  true,
  'Capitalize first letter after colon + space',
  'info',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_drug_name_case',
  'Tên thuốc chỉ viết hoa chữ cái đầu',
  NULL,
  'custom_ai',
  '{"prompt":"Find drug/medicine names written in ALL CAPS (e.g. PARACETAMOL, AMOXICILLIN, IBUPROFEN). Return [{original, correction}]."}'::jsonb,
  1,
  3,
  true,
  'Convert ALL CAPS drug names to Title Case (Paracetamol)',
  'info',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_double_space',
  'Không có 2 dấu cách liên tiếp',
  NULL,
  'regex',
  '{"pattern":"  +"}'::jsonb,
  1,
  1,
  true,
  'Replace multiple spaces with single space',
  'info',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_dash_spacing',
  'Dấu gạch ngang (-) giữa từ/số phải có khoảng cách',
  'VD đúng: "18 - 20 tuổi", "hay - vẫn". Ngoại lệ: tên riêng dùng gạch nối (mát-cơ-va) thì không cần khoảng cách.',
  'regex',
  '{"pattern":"(?<=[\\wđàáảãạăắằẳẵặâấầẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵ])-(?=[\\wđàáảãạăắằẳẵặâấầẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵ])","exclude_proper_nouns":true}'::jsonb,
  1,
  2,
  true,
  'Add spaces around dash: word-word → word - word (except proper noun hyphens)',
  'info',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_no_abbreviation',
  'Không dùng viết tắt thông thường',
  'Không dùng: "h" thay "giờ", "p" thay "phút", "s" thay "giây", "ntn" thay "như thế nào".',
  'regex',
  '{"pattern":"\\b(?:(?<=\\d)h(?=\\s|$|[,.])|(?<=\\d)p(?=\\s|$|[,.])|ntn|vs\\.)\\b","message":"Viết tắt không được dùng trong bài y tế"}'::jsonb,
  1,
  2,
  true,
  'Expand abbreviations: h→giờ, p→phút, ntn→như thế nào',
  'info',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'FORMAT'),
  'FORMAT_paragraph_length',
  'Đoạn văn không quá dài (≤150 từ)',
  NULL,
  'custom_ai',
  '{"prompt":"Find paragraphs exceeding 150 words. Return [{paragraph_preview, word_count, position}]."}'::jsonb,
  2,
  6,
  true,
  'Split long paragraphs into 2-3 shorter paragraphs at logical break points',
  'info',
  ARRAY['*'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'SOURCE'),
  'SOURCE_min_count',
  'Nguồn tham khảo: tối thiểu 3 link',
  NULL,
  'min_count',
  '{"field":"references","min":3}'::jsonb,
  3,
  3,
  false,
  NULL,
  'warning',
  ARRAY['BENH_LY','DUOC_LIEU','THUOC','DUOC_CHAT','VACCINE_LE','VACCINE_GOI'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'SOURCE'),
  'SOURCE_max_count',
  'Nguồn tham khảo: tối đa 5 link',
  NULL,
  'max_count',
  '{"field":"references","max":5}'::jsonb,
  1,
  1,
  false,
  NULL,
  'info',
  ARRAY['BENH_LY','DUOC_LIEU','THUOC','DUOC_CHAT','VACCINE_LE','VACCINE_GOI'],
  'global',
  false
),
(
  (SELECT id FROM rule_sections WHERE code = 'SOURCE'),
  'SOURCE_no_secondary',
  'Không dùng nguồn thứ cấp',
  'Không chấp nhận: blog cá nhân, báo điện tử trong nước, Wikipedia, web tổng hợp, mạng xã hội.',
  'reference_domain_check',
  '{"load_allowed_from":"rule_domain_configs.allowed_reference_domains","message":"Nguồn không thuộc danh sách được duyệt"}'::jsonb,
  3,
  9,
  false,
  NULL,
  'critical',
  ARRAY['BENH_LY','DUOC_LIEU','THUOC','DUOC_CHAT'],
  'global',
  true
),
(
  (SELECT id FROM rule_sections WHERE code = 'SOURCE'),
  'SOURCE_unlink_in_text',
  'Link nguồn tham khảo phải được unlink trong nội dung',
  'Trong phần nguồn tham khảo, các URL phải được hiển thị dưới dạng text thuần, không phải hyperlink có thể click.',
  'custom_ai',
  '{"prompt":"Check if reference section contains clickable hyperlinks (anchor tags) instead of plain text URLs. Return {has_linked_refs: bool, count: int}."}'::jsonb,
  2,
  2,
  true,
  'Convert anchor tags in references section to plain text: remove <a> tags, keep URL text',
  'warning',
  ARRAY['*'],
  'global',
  false
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  check_type = EXCLUDED.check_type,
  check_config = EXCLUDED.check_config,
  deduction = EXCLUDED.deduction,
  max_deduction = EXCLUDED.max_deduction,
  auto_fixable = EXCLUDED.auto_fixable,
  fix_instruction = EXCLUDED.fix_instruction,
  severity = EXCLUDED.severity,
  applies_to = EXCLUDED.applies_to,
  scope = EXCLUDED.scope,
  is_system = EXCLUDED.is_system;
