import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

// --- DB Mock Wrapper --- 
// TODO: Replace with real ORM (pg / Supabase) when ready
async function dbQuery<T = any>(query: string, params: any[] = []): Promise<T[]> {
  console.log(`[DB QUERY]: ${query.trim().substring(0, 50)}...`);
  return [];
}

/**
 * Extracts and records all citations generated by the AI within an article.
 * Connects the citations correctly to the internal KB or audits external hallucinated sources.
 */
export async function extractCitations(
  articleId: string, 
  generatedContent: string, 
  chunksUsed: any[]
) {
  // STEP 1 — Extract inline citations from content
  const model = genAI.getGenerativeModel({ 
      model: 'gemini-1.5-pro',
      generationConfig: { 
          responseMimeType: "application/json",
          temperature: 0.1 // Keep deterministic extraction
      }
  });
  
  const prompt = `Find all source citations in this article.
Return a JSON array of objects with the exact keys:
[{
  "cited_text": "the factual claim or paragraph segment from the article",
  "source_name": "name of the source document or title",
  "source_url": "URL if present, else empty string",
  "publisher": "publisher name or institution (e.g., WHO, CDC)",
  "year": 2023
}]

Article Content:
${generatedContent}
`;

  let extractedCitations: any[] = [];
  try {
     const res = await model.generateContent(prompt);
     const parsed = JSON.parse(res.response.text());
     if (Array.isArray(parsed)) extractedCitations = parsed;
  } catch (e) {
     console.error("Failed to extract citations with Gemini", e);
  }

  // Build allowedDomains từ 2 nguồn:
  // 1. Hardcoded fallback
  // 2. KB Group 1 sources (scope = 'general') — dynamic trusted domains
  const hardcodedDomains: string[] = [
      'who.int','cdc.gov','pubmed.ncbi.nlm.nih.gov','ncbi.nlm.nih.gov',
      'thelancet.com','nejm.org','bmj.com','uptodate.com',
      'emc.medicines.org.uk','mims.com','cochranelibrary.com'
  ];

  // Query Group 1 KB sources để lấy domain động
  const generalSources = await dbQuery<{ origin_url: string }>(
      `SELECT origin_url FROM kb_sources WHERE scope = 'general' AND is_active = true AND origin_url IS NOT NULL`
  );
  const dynamicDomains: string[] = generalSources
      .map(s => { try { return new URL(s.origin_url).hostname; } catch { return ''; } })
      .filter(Boolean);

  let allowedDomains: string[] = Array.from(new Set(hardcodedDomains.concat(dynamicDomains)));

  const report = {
    total_citations: 0,
    from_kb: 0,
    from_external: 0,
    unverified: 0,
    transparency_notes: [] as string[]
  };

  const processedRecords = [];

  // STEP 2 & 3 — Match citations and Validate
  for (const cit of extractedCitations) {
      let citation_type = 'ai_external';
      let matchedChunkId = null;
      let matchedSourceId = null;
      let transparencyNote = '';
      
      const citNameLower = (cit.source_name || '').toLowerCase();
      const citPubLower = (cit.publisher || '').toLowerCase();
      
      // Attempt to fuzzy match source_name to ANY chunk used in RAG
      const matchedChunk = (chunksUsed || []).find(c => {
         let meta = c.metadata;
         if (typeof meta === 'string') {
             try { meta = JSON.parse(meta); } catch(e) { meta = {}; }
         }
         
         const mTitle = (meta?.source_title || '').toLowerCase();
         const mPub = (c.publisher || meta?.publisher || '').toLowerCase();
         
         // Threshold match logic for internal KB hits
         return (citNameLower && mTitle.includes(citNameLower)) || 
                (mTitle && citNameLower.includes(mTitle)) ||
                (citPubLower && (mPub === citPubLower || citPubLower.includes(mPub)));
      });

      if (matchedChunk) {
          citation_type = 'kb_internal';
          matchedChunkId = matchedChunk.id;
          matchedSourceId = matchedChunk.source_id;
      } else {
          // Validate AI External Citation
          let isAllowed = false;
          if (cit.source_url) {
             const lowerUrl = cit.source_url.toLowerCase();
             isAllowed = allowedDomains.some(d => lowerUrl.includes(d.toLowerCase()));
          } else if (cit.publisher) {
             isAllowed = allowedDomains.some(d => d.toLowerCase().includes(citPubLower));
          }
          
          if (!isAllowed) {
              transparencyNote = 'unverified_source';
          } else {
              transparencyNote = 'verified_external';
          }
      }

      processedRecords.push({
          article_id: articleId,
          chunk_id: matchedChunkId,
          source_id: matchedSourceId,
          citation_type,
          cited_text: cit.cited_text,
          source_title: cit.source_name,
          source_url: cit.source_url,
          publisher: cit.publisher,
          publish_year: cit.year,
          transparency_note: transparencyNote
      });

      // Update counters directly
      report.total_citations++;
      if (citation_type === 'kb_internal') {
          report.from_kb++;
      } else {
          report.from_external++;
          if (transparencyNote === 'unverified_source') {
              report.unverified++;
          }
          
          // Formulate alert for external dependencies
          const noteText = `Nguồn bổ sung ngoài KB: [${cit.source_url || 'No URL'}] - [${cit.publisher || cit.source_name}] - [${cit.year || 'No Year'}]${transparencyNote === 'unverified_source' ? ' (CẢNH BÁO: Chưa được duyệt)' : ''}`;
          report.transparency_notes.push(noteText);
      }
  }

  // STEP 4 — Save to article_citations
  for (const record of processedRecords) {
      await dbQuery(`
         INSERT INTO article_citations (
           article_id, chunk_id, source_id, citation_type, 
           cited_text, source_title, source_url, publisher, 
           publish_year, transparency_note
         )
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      `, [
         record.article_id,
         record.chunk_id,
         record.source_id,
         record.citation_type,
         record.cited_text,
         record.source_title,
         record.source_url,
         record.publisher,
         record.publish_year,
         record.transparency_note
      ]);
  }

  // STEP 5 — Generate citation report
  return report;
}
